### ISSUE TITLE
URL Beacon issues

### ISSUE THREAD

**Issue by jsm174** [Beaconstac/EddystoneScanner-iOS-SDK#2]
Hello.  I tried to use the sample app and it doesn't seem to be detecting simple URL beacons.

Looking at the code:

https://github.com/Beaconstac/EddystoneScanner-iOS-SDK/blob/dd302bb73346bf50799e05951a5d4973f28e25f7/EddystoneScanner/Scanner.swift#L188-L208

It doesn't seem to have any add to nearbyBeacons list code.

Am I missing something?

**Comment by firecast** [comment]
Hi,

A beacon gets added to the list only when we detect a UID/EID frame from the beacon. The URL frame is used just to update the eddystoneURL associated with the beacon.

https://github.com/Beaconstac/EddystoneScanner-iOS-SDK/blob/dd302bb73346bf50799e05951a5d4973f28e25f7/EddystoneScanner/Scanner.swift#L160-L186 


Can you check if the beacon near you is configured for broadcasting Eddystone UID/EID frames?

**Comment by jsm174** [comment]
Thanks. I'm using a Raspberry PI 3 to act as the beacon. I am using: 

   https://github.com/don/node-eddystone-beacon

With that library you can advertise URLs without those frames.

**Comment by firecast** [comment]
Yup, that is possible with all BLE devices supporting Eddystone protocol. However, this was a design decision taken so that we can maintain a list of unique BLE devices in your proximity with an identifier that is only generated using the the UID/EID frame. 

You can make a fork of the repo and change the code to make it return Eddystone URL's on detection.
